### ISSUE TITLE
test_sun_vec_versus_telemetry always skipped?

### ISSUE THREAD

**Issue by jeanconn** [sot/kadi#127]
It looks to me like maybe

```
try:
    fetch.get_time_range('pitch')
    HAS_PITCH = True
except:
    HAS_PITCH = False
```

should be testing for dp_pitch instead of pitch, but I don't remember the history here.

**Comment by taldcroft** [comment]
Good point.  `fetch.Msid` knows that `pitch` is short-hand for `dp_pitch`, but apparently not `get_time_range`.  That's kind of an upstream bug, but easy to fix here.
