### ISSUE TITLE
events3.db3 is empty

### ISSUE THREAD

**Issue by jzuhone** [sot/kadi#153]
Fetching data using the latest version of kadi (5.0) does not appear to work since `$SKA/data/kadi/events3.db3` is empty.

**Comment by jeanconn** [comment]
@jzuhone This also speaks to the fact that I've felt free to "promote" unreleased individual packages to the "release" conda channel with the idea that only experienced users are working from there.  The plan is to promote kadi 5.0 to ska3/flight this week along with getting events3.db3 into SKA/data/kadi .  @taldcroft if you want to put the file there in advance you are welcome to do so I think.

**Comment by jzuhone** [comment]
I'm also happy to downgrade if that makes more sense.

**Comment by taldcroft** [comment]
I copied the latest `events3.db3` to `$SKA/data/kadi/` for testing purposes.   This is a one-time copy though as the original (being updated daily in a dev cron job) is at `/export/tom/miniconda3/envs/ska3-django3/data/kadi/events3.db3`.  That file is only visible on `kady`.

**Comment by taldcroft** [comment]
I set this up to rsync events3.db3 to /proj/sot/ska/data/kadi every day.  So that should be useable from now through when we promote.
