### ISSUE TITLE
Missing .git_archival.txt and .gitattributes

### ISSUE THREAD

**Issue by taldcroft** [sot/kadi#155]
Looks like this one missed getting the new .gitarchival.txt and .gitattributes files.  Probably my bad, but this needs to be fixed with a 5.0.1 for the MATLAB release because the zip download won't `python setup.py install`.

**Comment by jeanconn** [comment]
Since, if I understand correctly, these are just used on the github side and don't o into the conda packae, I'm not convinced it would be a horrible version control faux pas to retag 5.0...

**Comment by taldcroft** [comment]
Well I have that tag in at least 2 local repos by now, and I don't know off hand if that will be an issue.

There is nothing preventing ska3-matlab from using 5.0.1 while ska3-flight uses 5.0.0, but in practice there are more changes in the works like https://github.com/sot/proseco/pull/297 that we should get in for a release in both flight and matlab.

**Comment by taldcroft** [comment]
(Noting that from the Windows build perspective all that really matters right now is the version tag in ska3-matlab).
