### ISSUE TITLE
failure when deriving states from backstop commands on shiny

### ISSUE THREAD

**Issue by jzuhone** [sot/kadi#189]
the following script (run using shiny):

```python
from kadi import commands
from kadi.commands import states

# Get commands from JUN2720 from backstop
backstop_file = "/data/acis/LoadReviews/2020/JUL2720/oflsb/CR208_1806.backstop"
cmds = commands.get_cmds_from_backstop(backstop_file)

t = states.get_states(cmds=cmds, merge_identical=True)
```

produces the following traceback:

```pycon
Traceback (most recent call last):
  File "test_bs_cmds.py", line 8, in <module>
    t = states.get_states(cmds=cmds, merge_identical=True)
  File "/Users/jzuhone/miniconda3/envs/ska-shiny/lib/python3.8/site-packages/kadi/commands/states.py", line 1253, in get_states
    transitions = get_transitions_list(cmds, state_keys, start, stop, continuity)
  File "/Users/jzuhone/miniconda3/envs/ska-shiny/lib/python3.8/site-packages/kadi/commands/states.py", line 1128, in get_transitions_list
    transition_class.set_transitions(transitions_dict, cmds, start, stop)
  File "/Users/jzuhone/miniconda3/envs/ska-shiny/lib/python3.8/site-packages/kadi/commands/states.py", line 290, in set_transitions
    transitions_dict[date][name] = params[param_key]
KeyError: 'id'
```

Not sure if this is a bug or if I did something incorrect.

**Comment by jzuhone** [comment]
ping @taldcroft

**Comment by jzuhone** [comment]
An automatic script running on non-Shiny kadi has been failing today with the same error, so it looks like perhaps a database file is corrupted.

**Comment by jeanconn** [comment]
Thanks John, is the script doing something similar?

**Comment by jeanconn** [comment]
I can confirm that test_continuity_far_future looks to also be failing on kadi 5.2.0 in ska3-flight.

**Comment by taldcroft** [comment]
Grr. I understand now. In an effort to make the cmds.h5 as small as possible I made an index field that identifies unique command args be 2 bytes, but the number of unique commands has just gone over 65536.  Stupid over-optimization. I may be able to fix this soon, but I need to look a bit closer.
