### ISSUE TITLE
Migration to commands archive V2

### ISSUE THREAD

**Issue by taldcroft** [sot/kadi#216]
- [x] Make a beta release that has passed unit testing, functional testing, and code review.
- [x] Install with V1 being the default
- [x] Soak for 4 weeks.
  - [x] Confirm weekly update process
  - [x] Complete validation testing of the OBS commands
- [x] Update starcheck to default to `flight` on HEAD (https://github.com/sot/starcheck/pull/391)
- [x] New command sets `End SCS`, `End observing` and `End vehicle`
  - [x] Add options  to Command Events sheet
  - [x] Update TWiki docs
  - [x] Explicitly test events from test Google sheet
- [x] Command Events validation web app
  - [x] Need a way to allow In-work events (new config var)
- [x] Update kadi to set v2 as default (https://github.com/sot/kadi/pull/249)
- [x] Update ACIS thermal check (PR pending)
- [x] Promote the kadi release with V2 being the default in ska3-flight 2022.8.
  - [x] Make a backup of the current flight `cmds2.*`. 
  - [x] Copy `/home/aldcroft/tmp/kadi/cmds2.*` into `/proj/sot/ska/data/kadi`. This is the updated commands archive from https://github.com/sot/kadi/pull/248 which was validated.
  - [x] Manually run the update command to catch that file up to the present.

**Comment by jeanconn** [comment]
Should we just add a checkbox to do the FIXME at https://github.com/sot/kadi/blob/bf2c6a8d462f684edb8f0c44a4c1e845bf2c4e2e/kadi/commands/tests/test_commands.py#L290 as a last thing to do on this issue?

**Comment by jeanconn** [comment]
I think we also want some jobwatch checks and running validation.

**Comment by taldcroft** [comment]
All these items are done. Validation is tracked at https://github.com/sot/kadi/issues/272.
