### ISSUE TITLE
Broken Django links on the Getting Started page

### ISSUE THREAD

**Issue by Gregg140** [sot/kadi#235]
On your documentation page:

https://sot.github.io/kadi/events.html#getting-started
...under Advanced filtering

you have  a link "Making Queries".  This link 404's

Further down you have this link which also 404's: "Django Q objects"

**Comment by javierggt** [comment]
Thanks for the report,  Gregg.

Indeed that link is old and disappeared. This needs to be fixed.

In case it helps, these are the corresponding links for the actual django version currently used (replacing 1.5 by 3.1):
- https://docs.djangoproject.com/en/3.1/topics/db/queries/
- https://docs.djangoproject.com/en/3.1/topics/db/queries/#complex-lookups-with-q-objects
