### ISSUE TITLE
Validation plots don't display negative y values in the axis correctly

### ISSUE THREAD

**Issue by jeanconn** [sot/kadi#293]
<img width="91" alt="Screen Shot 2023-08-02 at 8 27 37 AM" src="https://github.com/sot/kadi/assets/791508/27480a69-fbb1-4a9d-b9f5-d512295c5262">
<img width="93" alt="Screen Shot 2023-08-02 at 8 27 28 AM" src="https://github.com/sot/kadi/assets/791508/8e6de61e-79b1-4520-9bb4-95b6cdd8d836">

**Comment by taldcroft** [comment]
This is a known upstream issue that should be fixed in the latest release of plotly.

- https://community.plotly.com/t/strange-negative-y-axis-values/73724.
- https://github.com/plotly/plotly.py/issues/4118
- https://github.com/plotly/plotly.py/pull/4114 (Fixed)

**Comment by taldcroft** [comment]
https://github.com/sot/skare3/issues/1140

**Comment by jeanconn** [comment]
Closed by https://github.com/sot/skare3/pull/1282
