### ISSUE TITLE
kadi states off_nom_roll validation can fail at far tail sun

### ISSUE THREAD

**Issue by taldcroft** [sot/kadi#329]
I don't understand why off_nom_roll is not tracking better. It seems like the state is not getting recomputed appropriately.

<img width="753" alt="image" src="https://github.com/sot/kadi/assets/348089/a66da45a-805f-4e0b-94c9-3bb7f4ede19d">

**Comment by jzuhone** [comment]
I have an idea about this that I'll try to check out

**Comment by taldcroft** [comment]
Sort of answering my question, it appears this attitude is at very far tail sun, pitch about 177.8 deg. The code breaks the state at least once every 10 ksec (or about 3 hours). The states are at around 00:30 and 03:20 and the dots shown above are not state breaks, instead they are breaks put in by the validation plotting.

So it is all basically working, but the math is just not in our favor at far tail sun with off_nom_roll getting squirrely. We could change that 10 ksec to 5 ksec.

**Comment by taldcroft** [comment]
Closing this unless the validation errors becomes a nuisance. Off nominal roll impacts xija thermal model solar heat via a factor of `sin(pitch)` , so an error of 5 deg at 177 pitch is negligible.

https://github.com/sot/xija/blob/dac36c2d0c12e5406d4c5bc7498f397e43ed0810/xija/component/heat/solar.py#L64
