### ISSUE TITLE
Master well ahead of installed 0.12.2

### ISSUE THREAD

**Issue by taldcroft** [sot/kadi#84]
In working on ska testing I discovered that kadi master is well ahead of the installed version.  The web branch is merged and then some updates related to LTT bad events.  This is all fine to install (I did a fairly careful review) but then I got hung up because it turns out the master version is really slow to import because it always imports mica.web and find_attitude, even though those are entirely unnecessary for event queries.

So for now no action is taken on this, but it does need to be cleaned up.  Worst case is accept a several second delay for import of kadi events.

**Comment by jeanconn** [comment]
Should the slow modules be conditionally imported in kadi, or did you want
to just make them faster modules, or both?

**Comment by taldcroft** [comment]
Ideally what I want is a way to know if kadi is being imported as part of web server process (in which case the optional apps are added to the installed apps list), or in a non-web application (no imports).  I discovered that the kadi self tests end up loading all installed apps.  I don't know offhand how to know if a django web app is running.

**Comment by jeanconn** [comment]
Regarding

> Ideally what I want is a way to know if kadi is being imported as part of web server process (in which case the optional apps are added to the installed apps list), or in a non-web application (no imports).

Would there be value in "cheating" and (instead of figuring this out from code in kadi after it is imported) just managing two versions of manage.py and kadi.settings?

**Comment by taldcroft** [comment]
This issue is still kind of relevant, though "installed" would refer to the installed version in the production kadi web server, which is at 3.12.2.  But #111 introduces a mechanism to check if running as the production web server.  There is also a reliable way to check if running the django dev server.  

Right now we are just taking the hit and importing `mica.web` and `find_attitude` when `kadi.events` gets imported.  It takes a few seconds.

**Comment by taldcroft** [comment]
This is no longer really a problem.
