### ISSUE TITLE
FTP tests in kadi look for 'user' in netrc

### ISSUE THREAD

**Issue by jeanconn** [sot/kadi#89]
I'm a bit confused at how this is supposed to work

https://github.com/sot/kadi/blob/bca2c85a03e3c07de9bdd31fad9fae81781d6344/kadi/tests/test_occweb.py#L22

    Ska.ftp.parse_netrc()['lucky']['user']

I've just got 'login' as my otherwise-working key in my .netrc, so I think looking for 'user' always fails and these tests don't run.  Is this just a typo or do you have a .netrc with a 'user' key @taldcroft (and then should I add the key / value pair or fix the tests or?)?

**Comment by taldcroft** [comment]
Good catch, that's just wrong.
